title: "AtomicSearch: AI Search Engine"
emoji: üîç
colorFrom: yellow
colorTo: yellow
sdk: docker
header: mini
short_description: "A AI Search Engine built with TS, React, and TensorFlow.js."
pinned: true
custom_headers:
  cross-origin-embedder-policy: require-corp
  cross-origin-opener-policy: same-origin
  cross-origin-resource-policy: cross-origin
